server:
  port: 8764

spring:
  application:
    name: service-ribbon
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      url: jdbc:mysql://rm-uf6mc44nmxz5492t9ho.mysql.rds.aliyuncs.com:3306/activiti?characterEncoding=utf8&useSSL=true
      username: root
      password: duoge123!@#
      driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus
mybatis-plus:
  global-config:
    id-type: 0
    #驼峰下划线转换
    db-column-underline: true
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    refresh-mapper: true
    field-strategy: 0
  mapper-locations: classpath:mapper/*.xml,mapper/*/*.xml
  type-aliases-package: com.sun.cloud.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#-----------------Hystrix配置-----------------------
hystrix:
  # === === === == 默认Command === === === ==
  command:
    default:
      execution:
        isolation:
          # 调用隔离方式, 默认: 采用线程隔离, ExecutionIsolationStrategy:THREAD
          strategy: THREAD
          # 调用超时时间, 默认: 5 秒
          thread:
            timeoutInMilliseconds: 8000
          # 使用信号量隔离时, 命令调用最大的并发数
          semaphore:
            maxConcurrentRequests: 10
      #使用信号量隔离时, 命令fallback调用最大的并发数
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 10
      # === === === == 熔断器 === === === ==
      circuitBreaker:
        # 熔断器在整个统计时间内是否开启的阀值, 默认20个请求
        requestVolumeThreshold: 8
        # 熔断器默认工作时间, 默认: 5 秒
        sleepWindowInMilliseconds: 5
        # 默认: 50%, 当出错率超过50% 后熔断器启动
        errorThresholdPercentage: 50
        # 是否强制开启熔断器阻断所有请求, 默认: false, 不开启
        forceOpen: false
        # 是否允许熔断器忽略错误, 默认false, 不开启
        forceClosed: false
  # === === === == 线程池 === === === ==
  threadPool:
    default:
      # 配置线程池大小, 默认值10个
      coreSize: 0
      # 配置队列长度, 默认-1使用SynchronousQueue,其他值则使用LinkedBlockingQueue:不可动态修改:
      maxQueueSize: -1
      # 队列拒绝的阈值,可通过修改这个变量动态修改允许排队的长度: maxQueueSize=-1时不适用:
      queueSizeRejectionThreshold: 5
      # 线程生存时间, 默认1分钟
      keepAliveTimeMinutes: 1
